on:
  pull_request:
    types: synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/github-script@0.8.0
     - with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Mastodonインスタンスの場合、ここで鯖缶確認を行ってください。 https://pr.0px.io/${context.issue.number}`
          })
